version: "3"
services: 
    server:
        build: .
        ports: 
            - "4000:4000"
        env_file: 
            - ./.env
        depends_on: 
            - postgres
    postgres:
        image: postgres
        volumes:
            - database-data:/var/lib/postgresql/data
        restart: always
        env_file:
            - ./.penv
volumes: 
    database-data: