version: "3"
version: "3"
services: 
    server:
        build:
            context: .
            args:
                NODE_ENV: development
        volumes: 
            - ./:/app:ro
            - ./app/node_modules
        environment: 
            - NODE_ENV=development
        command: npm run start